/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package telas;

/**
 *
 * @author Abner
 */
public class TelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
    }
    public TelaPrincipal(int acesso) {
        initComponents();
        this.acesso = acesso;
        limitarAcesso();
      }
    
    int acesso;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_senioridades = new javax.swing.JButton();
        btn_funcionarios = new javax.swing.JButton();
        btn_holerites = new javax.swing.JButton();
        btn_cargos = new javax.swing.JButton();
        jlb_sair = new javax.swing.JLabel();
        jlb_image2 = new javax.swing.JLabel();
        jlb_branco2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SFP_Principal");
        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMaximumSize(new java.awt.Dimension(830, 600));
        setResizable(false);
        getContentPane().setLayout(null);

        btn_senioridades.setBackground(new java.awt.Color(86, 153, 255));
        btn_senioridades.setFont(new java.awt.Font("SansSerif", 1, 40)); // NOI18N
        btn_senioridades.setForeground(new java.awt.Color(255, 255, 255));
        btn_senioridades.setText("SENIORIDADES");
        btn_senioridades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_senioridadesActionPerformed(evt);
            }
        });
        getContentPane().add(btn_senioridades);
        btn_senioridades.setBounds(520, 490, 590, 100);

        btn_funcionarios.setBackground(new java.awt.Color(86, 153, 255));
        btn_funcionarios.setFont(new java.awt.Font("SansSerif", 1, 40)); // NOI18N
        btn_funcionarios.setForeground(new java.awt.Color(255, 255, 255));
        btn_funcionarios.setText("FUNCIONÁRIOS");
        btn_funcionarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_funcionariosActionPerformed(evt);
            }
        });
        getContentPane().add(btn_funcionarios);
        btn_funcionarios.setBounds(520, 130, 590, 100);

        btn_holerites.setBackground(new java.awt.Color(86, 153, 255));
        btn_holerites.setFont(new java.awt.Font("SansSerif", 1, 40)); // NOI18N
        btn_holerites.setForeground(new java.awt.Color(255, 255, 255));
        btn_holerites.setText("HOLERITES");
        btn_holerites.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_holeritesActionPerformed(evt);
            }
        });
        getContentPane().add(btn_holerites);
        btn_holerites.setBounds(520, 250, 590, 100);

        btn_cargos.setBackground(new java.awt.Color(86, 153, 255));
        btn_cargos.setFont(new java.awt.Font("SansSerif", 1, 40)); // NOI18N
        btn_cargos.setForeground(new java.awt.Color(255, 255, 255));
        btn_cargos.setText("CARGOS");
        btn_cargos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cargosActionPerformed(evt);
            }
        });
        getContentPane().add(btn_cargos);
        btn_cargos.setBounds(520, 370, 590, 100);

        jlb_sair.setBackground(new java.awt.Color(86, 153, 255));
        jlb_sair.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jlb_sair.setForeground(new java.awt.Color(255, 255, 255));
        jlb_sair.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlb_sair.setText("SAIR");
        jlb_sair.setOpaque(true);
        jlb_sair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlb_sairMouseClicked(evt);
            }
        });
        getContentPane().add(jlb_sair);
        jlb_sair.setBounds(1170, 10, 70, 50);

        jlb_image2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/SFP_Principal.png"))); // NOI18N
        jlb_image2.setToolTipText("");
        jlb_image2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jlb_image2.setName(""); // NOI18N
        jlb_image2.setVerifyInputWhenFocusTarget(false);
        getContentPane().add(jlb_image2);
        jlb_image2.setBounds(0, -10, 425, 780);

        jlb_branco2.setBackground(new java.awt.Color(255, 255, 255));
        jlb_branco2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/SFP_Branco.png"))); // NOI18N
        jlb_branco2.setOpaque(true);
        getContentPane().add(jlb_branco2);
        jlb_branco2.setBounds(10, 0, 1250, 780);

        setSize(new java.awt.Dimension(1266, 788));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_cargosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cargosActionPerformed
        TelaCargo cargo = new TelaCargo(acesso);
        cargo.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_cargosActionPerformed

    private void btn_funcionariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_funcionariosActionPerformed
        TelaFuncionario funcionario = new TelaFuncionario(acesso);
        funcionario.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_funcionariosActionPerformed

    private void jlb_sairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlb_sairMouseClicked
        TelaLogin login = new TelaLogin();
        this.acesso = 1;
        login.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jlb_sairMouseClicked

    private void btn_holeritesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_holeritesActionPerformed
        TelaHolerite holerite = new TelaHolerite(acesso);
            holerite.setVisible(true);
            this.dispose();
    }//GEN-LAST:event_btn_holeritesActionPerformed

    private void btn_senioridadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_senioridadesActionPerformed
        TelaSenioridade senioridade = new TelaSenioridade(acesso);
        senioridade.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_senioridadesActionPerformed

    /**
     * Limitar acesso do usuario, dependendo do seu nivel de acesso. Bloqueia-se o acesso a 
     * geracao de pagamentos, deixando-o apenas executar cadastros/edicoes de funcionario, cargo e senioridade
     */
    public void limitarAcesso(){
        if (this.acesso == 0) btn_holerites.setEnabled(false); 
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cargos;
    private javax.swing.JButton btn_funcionarios;
    private javax.swing.JButton btn_holerites;
    private javax.swing.JButton btn_senioridades;
    private javax.swing.JLabel jlb_branco2;
    private javax.swing.JLabel jlb_image2;
    private javax.swing.JLabel jlb_sair;
    // End of variables declaration//GEN-END:variables
}
