/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package telas;

import javax.swing.JOptionPane;
 
/**
 *
 * @author Abner
 */
public class TelaLogin extends javax.swing.JFrame {
    
    public int acesso = 1;
    
    /**
     * Executa a validacao de acesso do usuario, alem de limita-lo
     */
    public void logar() {
       
        String txt_usuario = jtf_usuario.getText();
        String txt_senha = jlp_senha.getText();
                
        //livre acesso = 1
        String usuario = "admin";
        String senha = "12345";
        
        //acesso restrito = 0
        String usuario2 = "aux";
        String senha2 = "12345";
        
        if ((txt_usuario.equals(usuario) && txt_senha.equals(senha)) 
                || (txt_usuario.equals(usuario2) && txt_senha.equals(senha2))){
            if (txt_usuario.equals(usuario2)) acesso = 0;
            else acesso = 1;
            TelaPrincipal principal = new TelaPrincipal(acesso);
            principal.setVisible(true);
            this.dispose();
        } 

        else {
            JOptionPane.showMessageDialog(null, "Usuário e/ou senha inválido(s)");
        } //*/
    }
   
    public TelaLogin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jl_image1 = new javax.swing.JLabel();
        btn_entrar = new javax.swing.JButton();
        btn_esqueci = new javax.swing.JButton();
        btn_cadastro = new javax.swing.JButton();
        jlp_senha = new javax.swing.JPasswordField();
        jtf_usuario = new javax.swing.JTextField();
        jl_Usuario = new javax.swing.JLabel();
        jl_senha = new javax.swing.JLabel();
        jl_branco1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1250, 780));
        setPreferredSize(new java.awt.Dimension(1250, 780));
        setResizable(false);
        setSize(new java.awt.Dimension(1250, 780));
        getContentPane().setLayout(null);

        jl_image1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/SFP_Home.png"))); // NOI18N
        getContentPane().add(jl_image1);
        jl_image1.setBounds(0, -10, 425, 780);

        btn_entrar.setBackground(new java.awt.Color(86, 153, 255));
        btn_entrar.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        btn_entrar.setForeground(new java.awt.Color(255, 255, 255));
        btn_entrar.setText("ENTRAR");
        btn_entrar.setPreferredSize(new java.awt.Dimension(70, 25));
        btn_entrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_entrarActionPerformed(evt);
            }
        });
        btn_entrar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btn_entrarKeyPressed(evt);
            }
        });
        getContentPane().add(btn_entrar);
        btn_entrar.setBounds(470, 340, 160, 70);

        btn_esqueci.setBackground(new java.awt.Color(181, 210, 255));
        btn_esqueci.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_esqueci.setForeground(new java.awt.Color(0, 51, 159));
        btn_esqueci.setText("Esqueci minha senha!");
        btn_esqueci.setBorder(null);
        btn_esqueci.setBorderPainted(false);
        btn_esqueci.setEnabled(false);
        btn_esqueci.setMaximumSize(new java.awt.Dimension(145, 25));
        btn_esqueci.setMinimumSize(new java.awt.Dimension(145, 25));
        btn_esqueci.setPreferredSize(new java.awt.Dimension(145, 25));
        btn_esqueci.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_esqueciActionPerformed(evt);
            }
        });
        getContentPane().add(btn_esqueci);
        btn_esqueci.setBounds(470, 450, 170, 40);

        btn_cadastro.setBackground(new java.awt.Color(181, 210, 255));
        btn_cadastro.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_cadastro.setForeground(new java.awt.Color(0, 51, 159));
        btn_cadastro.setText("Solicitar cadastro!");
        btn_cadastro.setBorder(null);
        btn_cadastro.setBorderPainted(false);
        btn_cadastro.setEnabled(false);
        btn_cadastro.setPreferredSize(new java.awt.Dimension(145, 25));
        btn_cadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cadastroActionPerformed(evt);
            }
        });
        getContentPane().add(btn_cadastro);
        btn_cadastro.setBounds(670, 450, 170, 40);

        jlp_senha.setBackground(new java.awt.Color(181, 210, 255));
        jlp_senha.setFont(new java.awt.Font("SansSerif", 3, 14)); // NOI18N
        jlp_senha.setAlignmentX(0.0F);
        jlp_senha.setAlignmentY(0.0F);
        jlp_senha.setBorder(null);
        jlp_senha.setMaximumSize(new java.awt.Dimension(64, 25));
        jlp_senha.setPreferredSize(new java.awt.Dimension(30, 80));
        getContentPane().add(jlp_senha);
        jlp_senha.setBounds(485, 265, 450, 30);

        jtf_usuario.setBackground(new java.awt.Color(181, 210, 255));
        jtf_usuario.setFont(new java.awt.Font("SansSerif", 3, 16)); // NOI18N
        jtf_usuario.setAlignmentX(0.0F);
        jtf_usuario.setAlignmentY(0.0F);
        jtf_usuario.setAutoscrolls(false);
        jtf_usuario.setBorder(null);
        jtf_usuario.setMaximumSize(new java.awt.Dimension(64, 25));
        jtf_usuario.setPreferredSize(new java.awt.Dimension(30, 80));
        jtf_usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtf_usuarioActionPerformed(evt);
            }
        });
        getContentPane().add(jtf_usuario);
        jtf_usuario.setBounds(485, 124, 450, 30);

        jl_Usuario.setBackground(new java.awt.Color(86, 153, 255));
        jl_Usuario.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jl_Usuario.setForeground(new java.awt.Color(255, 255, 255));
        jl_Usuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/LBL_Usuario.png"))); // NOI18N
        jl_Usuario.setText("   USUÁRIO");
        jl_Usuario.setToolTipText("");
        jl_Usuario.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jl_Usuario.setAlignmentX(0.5F);
        jl_Usuario.setMaximumSize(new java.awt.Dimension(60, 25));
        jl_Usuario.setMinimumSize(new java.awt.Dimension(60, 25));
        jl_Usuario.setOpaque(true);
        jl_Usuario.setPreferredSize(new java.awt.Dimension(60, 25));
        jl_Usuario.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        getContentPane().add(jl_Usuario);
        jl_Usuario.setBounds(470, 80, 520, 90);

        jl_senha.setBackground(new java.awt.Color(86, 153, 255));
        jl_senha.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jl_senha.setForeground(new java.awt.Color(255, 255, 255));
        jl_senha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/LBL_Senha.png"))); // NOI18N
        jl_senha.setText("   SENHA");
        jl_senha.setToolTipText("");
        jl_senha.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jl_senha.setMaximumSize(new java.awt.Dimension(60, 25));
        jl_senha.setMinimumSize(new java.awt.Dimension(60, 25));
        jl_senha.setOpaque(true);
        jl_senha.setPreferredSize(new java.awt.Dimension(60, 25));
        getContentPane().add(jl_senha);
        jl_senha.setBounds(470, 220, 520, 90);

        jl_branco1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/SFP_Branco.png"))); // NOI18N
        getContentPane().add(jl_branco1);
        jl_branco1.setBounds(0, 0, 1920, 1080);

        getAccessibleContext().setAccessibleDescription("");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_entrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_entrarActionPerformed
        logar();
    }//GEN-LAST:event_btn_entrarActionPerformed

    private void btn_esqueciActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_esqueciActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_esqueciActionPerformed

    private void btn_cadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cadastroActionPerformed
        TelaCadastro senha = new TelaCadastro();
        senha.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_cadastroActionPerformed

    private void jtf_usuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtf_usuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_usuarioActionPerformed

    private void btn_entrarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btn_entrarKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_entrarKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cadastro;
    private javax.swing.JButton btn_entrar;
    private javax.swing.JButton btn_esqueci;
    private javax.swing.JLabel jl_Usuario;
    private javax.swing.JLabel jl_branco1;
    private javax.swing.JLabel jl_image1;
    private javax.swing.JLabel jl_senha;
    private javax.swing.JPasswordField jlp_senha;
    private javax.swing.JTextField jtf_usuario;
    // End of variables declaration//GEN-END:variables
}
