package telas;

import banco.SenioridadeDAO;
import entidades.Senioridade;
import java.awt.Color;
import java.text.DecimalFormat;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Abner
 */
public class TelaSenioridade extends javax.swing.JFrame {

    /**
     * Creates new form TelaUsuario
     */
    public TelaSenioridade() {
        initComponents();
    }
    
    public TelaSenioridade(int acesso) {
        initComponents();
        this.acesso = acesso;
    }
    int acesso;
    int codSenioridade;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnl_background = new javax.swing.JPanel();
        jlb_visualizar = new javax.swing.JLabel();
        pnl_default = new javax.swing.JPanel();
        pnl_visualizar = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblSenioridades = new javax.swing.JTable();
        jtf_nome = new javax.swing.JTextField();
        jtf_porcentagem = new javax.swing.JTextField();
        btn_editar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jlb_voltar3 = new javax.swing.JLabel();
        jlb_image32 = new javax.swing.JLabel();
        jlb_image3 = new javax.swing.JLabel();
        jlb_branco3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(null);

        pnl_background.setBackground(new java.awt.Color(181, 210, 255));
        pnl_background.setLayout(null);

        jlb_visualizar.setBackground(new java.awt.Color(181, 210, 255));
        jlb_visualizar.setFont(new java.awt.Font("SansSerif", 3, 18)); // NOI18N
        jlb_visualizar.setForeground(new java.awt.Color(25, 39, 70));
        jlb_visualizar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlb_visualizar.setText("VISUALIZAR SENIORIDADE");
        jlb_visualizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jlb_visualizar.setOpaque(true);
        jlb_visualizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlb_visualizarMouseClicked(evt);
            }
        });
        pnl_background.add(jlb_visualizar);
        jlb_visualizar.setBounds(0, 0, 770, 60);

        pnl_default.setBackground(new java.awt.Color(255, 255, 255));
        pnl_default.setAutoscrolls(true);
        pnl_background.add(pnl_default);
        pnl_default.setBounds(0, 0, 770, 570);

        pnl_visualizar.setBackground(new java.awt.Color(181, 210, 255));
        pnl_visualizar.setMinimumSize(new java.awt.Dimension(770, 510));
        pnl_visualizar.setLayout(null);

        tblSenioridades.setBackground(new java.awt.Color(86, 153, 220));
        tblSenioridades.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        tblSenioridades.setFont(new java.awt.Font("SansSerif", 3, 14)); // NOI18N
        tblSenioridades.setForeground(new java.awt.Color(255, 255, 255));
        tblSenioridades.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Código", "Nome", "Porcentagem de Reconhecimento"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblSenioridades.setMinimumSize(new java.awt.Dimension(45, 104));
        tblSenioridades.setPreferredSize(new java.awt.Dimension(225, 104));
        tblSenioridades.setRowHeight(26);
        tblSenioridades.setSelectionBackground(new java.awt.Color(255, 255, 255));
        tblSenioridades.setSelectionForeground(new java.awt.Color(0, 10, 125));
        tblSenioridades.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tblSenioridades.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tblSenioridades.setShowGrid(true);
        tblSenioridades.setShowHorizontalLines(false);
        tblSenioridades.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblSenioridadesMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblSenioridades);

        pnl_visualizar.add(jScrollPane2);
        jScrollPane2.setBounds(0, 40, 770, 110);

        jtf_nome.setEditable(false);
        jtf_nome.setBackground(new java.awt.Color(217, 227, 244));
        jtf_nome.setFont(new java.awt.Font("SansSerif", 3, 18)); // NOI18N
        jtf_nome.setBorder(null);
        pnl_visualizar.add(jtf_nome);
        jtf_nome.setBounds(50, 206, 300, 20);

        jtf_porcentagem.setBackground(new java.awt.Color(217, 227, 244));
        jtf_porcentagem.setFont(new java.awt.Font("SansSerif", 3, 18)); // NOI18N
        jtf_porcentagem.setBorder(null);
        pnl_visualizar.add(jtf_porcentagem);
        jtf_porcentagem.setBounds(400, 206, 300, 20);

        btn_editar.setBackground(new java.awt.Color(91, 225, 64));
        btn_editar.setFont(new java.awt.Font("SansSerif", 3, 25)); // NOI18N
        btn_editar.setForeground(new java.awt.Color(255, 255, 255));
        btn_editar.setText("Editar");
        btn_editar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_editarActionPerformed(evt);
            }
        });
        pnl_visualizar.add(btn_editar);
        btn_editar.setBounds(560, 390, 150, 70);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Tela_Senioridades.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        pnl_visualizar.add(jLabel2);
        jLabel2.setBounds(10, 170, 750, 280);

        pnl_background.add(pnl_visualizar);
        pnl_visualizar.setBounds(0, 60, 770, 510);
        pnl_visualizar.getAccessibleContext().setAccessibleDescription("");

        getContentPane().add(pnl_background);
        pnl_background.setBounds(440, 170, 770, 570);

        jlb_voltar3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/BTN_voltar.png"))); // NOI18N
        jlb_voltar3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jlb_voltar3.setOpaque(true);
        jlb_voltar3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlb_voltar3MouseClicked(evt);
            }
        });
        getContentPane().add(jlb_voltar3);
        jlb_voltar3.setBounds(440, 45, 100, 90);

        jlb_image32.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/LBL_Senioridade.png"))); // NOI18N
        getContentPane().add(jlb_image32);
        jlb_image32.setBounds(545, 40, 590, 100);

        jlb_image3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/SFP_Cargo.png"))); // NOI18N
        getContentPane().add(jlb_image3);
        jlb_image3.setBounds(0, -10, 425, 780);

        jlb_branco3.setBackground(new java.awt.Color(255, 255, 255));
        jlb_branco3.setOpaque(true);
        getContentPane().add(jlb_branco3);
        jlb_branco3.setBounds(0, 0, 1250, 780);

        setSize(new java.awt.Dimension(1266, 788));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jlb_visualizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlb_visualizarMouseClicked
        pnl_default.setVisible(false);
        pnl_visualizar.setVisible(true);
        jlb_visualizar.setBackground(new Color(25,39,70));
        jlb_visualizar.setForeground(Color.white);
        preencherTab();
    }//GEN-LAST:event_jlb_visualizarMouseClicked

    private void jlb_voltar3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlb_voltar3MouseClicked
        TelaPrincipal principal = new TelaPrincipal(acesso);
        principal.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jlb_voltar3MouseClicked

    private void tblSenioridadesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblSenioridadesMouseClicked
        if (tblSenioridades.getSelectedRow() != -1){
        codSenioridade = Integer.parseInt(tblSenioridades.getValueAt(tblSenioridades.getSelectedRow(), 0).toString());
	jtf_nome.setText(tblSenioridades.getValueAt(tblSenioridades.getSelectedRow(), 1).toString());
	jtf_porcentagem.setText(tblSenioridades.getValueAt(tblSenioridades.getSelectedRow(), 2).toString());      
}
    }//GEN-LAST:event_tblSenioridadesMouseClicked

    private void btn_editarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editarActionPerformed
        String nome;
        float porc;
        
        nome = jtf_nome.getText();
	porc = Float.parseFloat(jtf_porcentagem.getText());
        porc /= 100;
        Senioridade sen = new Senioridade(nome, porc);
        
        SenioridadeDAO dao = new SenioridadeDAO();
        JOptionPane.showMessageDialog(null, dao.editar(sen, codSenioridade));
        
        jtf_nome.setText("");
        jtf_porcentagem.setText("");
        
        preencherTab();
    }//GEN-LAST:event_btn_editarActionPerformed

    /**
     * Busca os dados no banco para preenchimento de tabela
     */
     private void preencherTab()
    {
        SenioridadeDAO sen = new SenioridadeDAO();
        List<Senioridade> listaSen = sen.listar("SELECT * FROM senioridade");
        
        DefaultTableModel tabelaSen = (DefaultTableModel) tblSenioridades.getModel();
        
        tabelaSen.setNumRows(0);
        for (Senioridade s : listaSen)
        {
            Object[] obj = new Object[]{
            
            s.getCodigo(), s.getNivel(), duasCasas(s.getPorcentagem_rec()*100)};
            
            tabelaSen.addRow(obj);
        }
    }
     
     /**
     * Faz a conversao de um valor float para decimal format com duas casas decimais
     * @param var - valor para conversao
     * @return valor convertido
     */
    public String duasCasas(float var){
        DecimalFormat df = new DecimalFormat("0.00");
        return df.format(var);
    }
     
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaSenioridade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaSenioridade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaSenioridade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaSenioridade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaSenioridade().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_editar;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel jlb_branco3;
    private javax.swing.JLabel jlb_image3;
    private javax.swing.JLabel jlb_image32;
    private javax.swing.JLabel jlb_visualizar;
    private javax.swing.JLabel jlb_voltar3;
    private javax.swing.JTextField jtf_nome;
    private javax.swing.JTextField jtf_porcentagem;
    private javax.swing.JPanel pnl_background;
    private javax.swing.JPanel pnl_default;
    private javax.swing.JPanel pnl_visualizar;
    private javax.swing.JTable tblSenioridades;
    // End of variables declaration//GEN-END:variables
}
