/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package telas;

import java.sql.*;
import banco.BD;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
 
/**
 *
 * @author Abner
 */
public class TelaCadastro extends javax.swing.JFrame {

    Connection con = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    private BD bd;
    
    /**
     * Limpa caixas de textos
     */
    private void limpar(){
        jtf_cadastrarCod.setText(null);
        jtf_cadastrarEmail.setText(null);
        jtf_cadastrarUsuario.setText(null);
        jlp_cadastrarSenha.setText(null);
    }
    
    private void cadastrar(){
        String sql = "INSERTO INTO tbUsuario(codUsuario, nomeUsuario, emailUsuario, senhaUsuario) VALUES(?,?,?,?)";
        
        try{
            pst = con.prepareStatement(sql);
            pst.setString(1,jtf_cadastrarCod.getText());
            pst.setString(2,jtf_cadastrarEmail.getText());
            pst.setString(3,jtf_cadastrarUsuario.getText());
            pst.setString(4,jlp_cadastrarSenha.getText());  
           
            if ((jtf_cadastrarCod.getText().isEmpty()) || (jtf_cadastrarEmail.getText().isEmpty()) || 
                    (jtf_cadastrarUsuario.getText().isEmpty()) || (jlp_cadastrarSenha.getText().isEmpty())){
                JOptionPane.showMessageDialog(null,"Preenhca todos os campos!");
            } else {
            int cadastrado = pst.executeUpdate();
            
            if (cadastrado > 0){
                JOptionPane.showMessageDialog(null,"Usuário cadastrado com sucesso!");
                limpar();
            }
        }
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }

    public TelaCadastro() {
        initComponents();
        bd = new BD();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jl_image12 = new javax.swing.JLabel();
        btn_cancelarCad = new javax.swing.JButton();
        btn_cadastrarCad = new javax.swing.JButton();
        jtf_cadastrarCod = new javax.swing.JTextField();
        jtf_cadastrarEmail = new javax.swing.JTextField();
        jtf_cadastrarUsuario = new javax.swing.JTextField();
        jlp_cadastrarSenha = new javax.swing.JPasswordField();
        jlb_codigo = new javax.swing.JLabel();
        jl_emailCad = new javax.swing.JLabel();
        jl_UsuarioCad = new javax.swing.JLabel();
        jl_senhaCad = new javax.swing.JLabel();
        jl_branco12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1250, 780));
        setPreferredSize(new java.awt.Dimension(1250, 780));
        setResizable(false);
        setSize(new java.awt.Dimension(1250, 780));
        getContentPane().setLayout(null);

        jl_image12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/SFP_Cadastrar.png"))); // NOI18N
        getContentPane().add(jl_image12);
        jl_image12.setBounds(0, -10, 425, 780);

        btn_cancelarCad.setBackground(new java.awt.Color(86, 153, 255));
        btn_cancelarCad.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        btn_cancelarCad.setForeground(new java.awt.Color(255, 255, 255));
        btn_cancelarCad.setText("CANCELAR");
        btn_cancelarCad.setPreferredSize(new java.awt.Dimension(70, 25));
        btn_cancelarCad.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_cancelarCadMouseClicked(evt);
            }
        });
        btn_cancelarCad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelarCadActionPerformed(evt);
            }
        });
        getContentPane().add(btn_cancelarCad);
        btn_cancelarCad.setBounds(750, 520, 250, 70);

        btn_cadastrarCad.setBackground(new java.awt.Color(86, 153, 255));
        btn_cadastrarCad.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        btn_cadastrarCad.setForeground(new java.awt.Color(255, 255, 255));
        btn_cadastrarCad.setText("CADASTRAR");
        btn_cadastrarCad.setPreferredSize(new java.awt.Dimension(70, 25));
        btn_cadastrarCad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cadastrarCadActionPerformed(evt);
            }
        });
        getContentPane().add(btn_cadastrarCad);
        btn_cadastrarCad.setBounds(480, 520, 250, 70);

        jtf_cadastrarCod.setBackground(new java.awt.Color(181, 210, 255));
        jtf_cadastrarCod.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jtf_cadastrarCod.setBorder(null);
        jtf_cadastrarCod.setOpaque(true);
        getContentPane().add(jtf_cadastrarCod);
        jtf_cadastrarCod.setBounds(490, 67, 300, 15);

        jtf_cadastrarEmail.setBackground(new java.awt.Color(181, 210, 255));
        jtf_cadastrarEmail.setFont(new java.awt.Font("SansSerif", 3, 16)); // NOI18N
        jtf_cadastrarEmail.setAlignmentX(0.0F);
        jtf_cadastrarEmail.setAlignmentY(0.0F);
        jtf_cadastrarEmail.setAutoscrolls(false);
        jtf_cadastrarEmail.setBorder(null);
        jtf_cadastrarEmail.setMaximumSize(new java.awt.Dimension(64, 25));
        jtf_cadastrarEmail.setPreferredSize(new java.awt.Dimension(30, 80));
        jtf_cadastrarEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtf_cadastrarEmailActionPerformed(evt);
            }
        });
        getContentPane().add(jtf_cadastrarEmail);
        jtf_cadastrarEmail.setBounds(495, 155, 490, 30);

        jtf_cadastrarUsuario.setBackground(new java.awt.Color(181, 210, 255));
        jtf_cadastrarUsuario.setFont(new java.awt.Font("SansSerif", 3, 16)); // NOI18N
        jtf_cadastrarUsuario.setAlignmentX(0.0F);
        jtf_cadastrarUsuario.setAlignmentY(0.0F);
        jtf_cadastrarUsuario.setAutoscrolls(false);
        jtf_cadastrarUsuario.setBorder(null);
        jtf_cadastrarUsuario.setMaximumSize(new java.awt.Dimension(64, 25));
        jtf_cadastrarUsuario.setPreferredSize(new java.awt.Dimension(30, 80));
        jtf_cadastrarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtf_cadastrarUsuarioActionPerformed(evt);
            }
        });
        getContentPane().add(jtf_cadastrarUsuario);
        jtf_cadastrarUsuario.setBounds(505, 295, 450, 30);

        jlp_cadastrarSenha.setBackground(new java.awt.Color(181, 210, 255));
        jlp_cadastrarSenha.setFont(new java.awt.Font("SansSerif", 3, 14)); // NOI18N
        jlp_cadastrarSenha.setAlignmentX(0.0F);
        jlp_cadastrarSenha.setAlignmentY(0.0F);
        jlp_cadastrarSenha.setBorder(null);
        jlp_cadastrarSenha.setMaximumSize(new java.awt.Dimension(64, 25));
        jlp_cadastrarSenha.setPreferredSize(new java.awt.Dimension(30, 80));
        getContentPane().add(jlp_cadastrarSenha);
        jlp_cadastrarSenha.setBounds(500, 435, 450, 30);

        jlb_codigo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/LBL_Código.png"))); // NOI18N
        jlb_codigo.setText("Código");
        jlb_codigo.setOpaque(true);
        getContentPane().add(jlb_codigo);
        jlb_codigo.setBounds(480, 40, 360, 50);

        jl_emailCad.setBackground(new java.awt.Color(86, 153, 255));
        jl_emailCad.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jl_emailCad.setForeground(new java.awt.Color(255, 255, 255));
        jl_emailCad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/LBL_CadEmail.png"))); // NOI18N
        jl_emailCad.setText("   SENHA");
        jl_emailCad.setToolTipText("");
        jl_emailCad.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jl_emailCad.setMaximumSize(new java.awt.Dimension(60, 25));
        jl_emailCad.setMinimumSize(new java.awt.Dimension(60, 25));
        jl_emailCad.setOpaque(true);
        jl_emailCad.setPreferredSize(new java.awt.Dimension(60, 25));
        getContentPane().add(jl_emailCad);
        jl_emailCad.setBounds(480, 110, 520, 90);

        jl_UsuarioCad.setBackground(new java.awt.Color(86, 153, 255));
        jl_UsuarioCad.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jl_UsuarioCad.setForeground(new java.awt.Color(255, 255, 255));
        jl_UsuarioCad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/LBL_CadUsuário.png"))); // NOI18N
        jl_UsuarioCad.setText("   USUÁRIO");
        jl_UsuarioCad.setToolTipText("");
        jl_UsuarioCad.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jl_UsuarioCad.setAlignmentX(0.5F);
        jl_UsuarioCad.setMaximumSize(new java.awt.Dimension(60, 25));
        jl_UsuarioCad.setMinimumSize(new java.awt.Dimension(60, 25));
        jl_UsuarioCad.setOpaque(true);
        jl_UsuarioCad.setPreferredSize(new java.awt.Dimension(60, 25));
        jl_UsuarioCad.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        getContentPane().add(jl_UsuarioCad);
        jl_UsuarioCad.setBounds(480, 250, 520, 90);

        jl_senhaCad.setBackground(new java.awt.Color(86, 153, 255));
        jl_senhaCad.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jl_senhaCad.setForeground(new java.awt.Color(255, 255, 255));
        jl_senhaCad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/LBL_CadSenha.png"))); // NOI18N
        jl_senhaCad.setText("   SENHA");
        jl_senhaCad.setToolTipText("");
        jl_senhaCad.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jl_senhaCad.setMaximumSize(new java.awt.Dimension(60, 25));
        jl_senhaCad.setMinimumSize(new java.awt.Dimension(60, 25));
        jl_senhaCad.setOpaque(true);
        jl_senhaCad.setPreferredSize(new java.awt.Dimension(60, 25));
        getContentPane().add(jl_senhaCad);
        jl_senhaCad.setBounds(480, 390, 520, 90);

        jl_branco12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/SFP_Branco.png"))); // NOI18N
        getContentPane().add(jl_branco12);
        jl_branco12.setBounds(0, 0, 1920, 1080);

        getAccessibleContext().setAccessibleDescription("");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_cadastrarCadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cadastrarCadActionPerformed
        cadastrar();
    }//GEN-LAST:event_btn_cadastrarCadActionPerformed

    private void jtf_cadastrarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtf_cadastrarUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_cadastrarUsuarioActionPerformed

    private void btn_cancelarCadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelarCadActionPerformed
        limpar();
    }//GEN-LAST:event_btn_cancelarCadActionPerformed

    private void jtf_cadastrarEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtf_cadastrarEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_cadastrarEmailActionPerformed

    private void btn_cancelarCadMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_cancelarCadMouseClicked
        TelaLogin login = new TelaLogin();
            login.setVisible(true);
            this.dispose();
    }//GEN-LAST:event_btn_cancelarCadMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCadastro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cadastrarCad;
    private javax.swing.JButton btn_cancelarCad;
    private javax.swing.JLabel jl_UsuarioCad;
    private javax.swing.JLabel jl_branco12;
    private javax.swing.JLabel jl_emailCad;
    private javax.swing.JLabel jl_image12;
    private javax.swing.JLabel jl_senhaCad;
    private javax.swing.JLabel jlb_codigo;
    private javax.swing.JPasswordField jlp_cadastrarSenha;
    private javax.swing.JTextField jtf_cadastrarCod;
    private javax.swing.JTextField jtf_cadastrarEmail;
    private javax.swing.JTextField jtf_cadastrarUsuario;
    // End of variables declaration//GEN-END:variables
}
