package telas;

import banco.CargoDAO;
import entidades.Cargo;
import java.awt.Color;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Abner
 */
public class TelaCargo extends javax.swing.JFrame {

    /**
     * Creates new form TelaUsuario
     */
    public TelaCargo() {
        initComponents();
    }
    public TelaCargo(int acesso) {
        initComponents();
        this.acesso = acesso;
    }
    int acesso;
    int codCargo;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnl_background = new javax.swing.JPanel();
        jlb_visualizar = new javax.swing.JLabel();
        jlb_cadastrar = new javax.swing.JLabel();
        pnl_default = new javax.swing.JPanel();
        pnl_cadastrar = new javax.swing.JPanel();
        jtf_nome = new javax.swing.JTextField();
        jtf_salario = new javax.swing.JTextField();
        jtf_codigo = new javax.swing.JTextField();
        jlb_nome = new javax.swing.JLabel();
        jlb_salario = new javax.swing.JLabel();
        btn_cancelar = new javax.swing.JButton();
        btn_salvar = new javax.swing.JButton();
        pnl_visualizar = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblCargos = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jtf_Filtro = new javax.swing.JTextField();
        jtf_nomeEditar = new javax.swing.JTextField();
        jtf_valorEditar = new javax.swing.JTextField();
        btn_editar = new javax.swing.JButton();
        btn_excluir = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jlb_voltar3 = new javax.swing.JLabel();
        jlb_image32 = new javax.swing.JLabel();
        jlb_image3 = new javax.swing.JLabel();
        jlb_branco3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1679, 1566));
        setResizable(false);
        getContentPane().setLayout(null);

        pnl_background.setBackground(new java.awt.Color(181, 210, 255));
        pnl_background.setLayout(null);

        jlb_visualizar.setBackground(new java.awt.Color(181, 210, 255));
        jlb_visualizar.setFont(new java.awt.Font("SansSerif", 3, 18)); // NOI18N
        jlb_visualizar.setForeground(new java.awt.Color(25, 39, 70));
        jlb_visualizar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlb_visualizar.setText("VISUALIZAR CARGO");
        jlb_visualizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jlb_visualizar.setOpaque(true);
        jlb_visualizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlb_visualizarMouseClicked(evt);
            }
        });
        pnl_background.add(jlb_visualizar);
        jlb_visualizar.setBounds(390, 0, 380, 60);

        jlb_cadastrar.setBackground(new java.awt.Color(181, 210, 255));
        jlb_cadastrar.setFont(new java.awt.Font("SansSerif", 3, 18)); // NOI18N
        jlb_cadastrar.setForeground(new java.awt.Color(25, 39, 70));
        jlb_cadastrar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlb_cadastrar.setText("CADASTRAR CARGO");
        jlb_cadastrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jlb_cadastrar.setOpaque(true);
        jlb_cadastrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlb_cadastrarMouseClicked(evt);
            }
        });
        pnl_background.add(jlb_cadastrar);
        jlb_cadastrar.setBounds(0, 0, 380, 60);

        pnl_default.setBackground(new java.awt.Color(255, 255, 255));
        pnl_default.setAutoscrolls(true);
        pnl_background.add(pnl_default);
        pnl_default.setBounds(0, 0, 770, 570);

        pnl_cadastrar.setBackground(new java.awt.Color(181, 210, 255));
        pnl_cadastrar.setLayout(null);

        jtf_nome.setBackground(new java.awt.Color(217, 227, 244));
        jtf_nome.setFont(new java.awt.Font("SansSerif", 3, 16)); // NOI18N
        jtf_nome.setAutoscrolls(false);
        jtf_nome.setBorder(null);
        jtf_nome.setEnabled(false);
        pnl_cadastrar.add(jtf_nome);
        jtf_nome.setBounds(50, 90, 660, 30);

        jtf_salario.setBackground(new java.awt.Color(217, 227, 244));
        jtf_salario.setFont(new java.awt.Font("SansSerif", 3, 26)); // NOI18N
        jtf_salario.setForeground(new java.awt.Color(0, 51, 159));
        jtf_salario.setAutoscrolls(false);
        jtf_salario.setBorder(null);
        jtf_salario.setEnabled(false);
        pnl_cadastrar.add(jtf_salario);
        jtf_salario.setBounds(90, 230, 250, 40);

        jtf_codigo.setBackground(new java.awt.Color(181, 210, 255));
        jtf_codigo.setFont(new java.awt.Font("SansSerif", 3, 14)); // NOI18N
        jtf_codigo.setAutoscrolls(false);
        jtf_codigo.setBorder(null);
        jtf_codigo.setEnabled(false);
        pnl_cadastrar.add(jtf_codigo);
        jtf_codigo.setBounds(50, 446, 320, 17);

        jlb_nome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/LBL_Cargo.png"))); // NOI18N
        pnl_cadastrar.add(jlb_nome);
        jlb_nome.setBounds(30, 30, 720, 110);

        jlb_salario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/LBL_Salario.png"))); // NOI18N
        jlb_salario.setText("Salário Hora");
        jlb_salario.setOpaque(true);
        pnl_cadastrar.add(jlb_salario);
        jlb_salario.setBounds(30, 180, 340, 110);

        btn_cancelar.setBackground(new java.awt.Color(242, 172, 52));
        btn_cancelar.setFont(new java.awt.Font("SansSerif", 1, 25)); // NOI18N
        btn_cancelar.setText("Cancelar");
        btn_cancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_cancelar.setFocusPainted(false);
        btn_cancelar.setFocusable(false);
        btn_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelarActionPerformed(evt);
            }
        });
        pnl_cadastrar.add(btn_cancelar);
        btn_cancelar.setBounds(600, 400, 150, 70);

        btn_salvar.setBackground(new java.awt.Color(91, 225, 64));
        btn_salvar.setFont(new java.awt.Font("SansSerif", 3, 25)); // NOI18N
        btn_salvar.setForeground(new java.awt.Color(255, 255, 255));
        btn_salvar.setText("Salvar");
        btn_salvar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_salvar.setFocusPainted(false);
        btn_salvar.setFocusable(false);
        btn_salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_salvarActionPerformed(evt);
            }
        });
        pnl_cadastrar.add(btn_salvar);
        btn_salvar.setBounds(420, 400, 150, 70);

        pnl_background.add(pnl_cadastrar);
        pnl_cadastrar.setBounds(0, 60, 770, 510);

        pnl_visualizar.setBackground(new java.awt.Color(181, 210, 255));
        pnl_visualizar.setMinimumSize(new java.awt.Dimension(770, 510));
        pnl_visualizar.setLayout(null);

        tblCargos.setBackground(new java.awt.Color(86, 153, 220));
        tblCargos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        tblCargos.setFont(new java.awt.Font("SansSerif", 3, 14)); // NOI18N
        tblCargos.setForeground(new java.awt.Color(255, 255, 255));
        tblCargos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Código", "Nome", "Valor por Hora"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblCargos.setRowHeight(26);
        tblCargos.setSelectionBackground(new java.awt.Color(255, 255, 255));
        tblCargos.setSelectionForeground(new java.awt.Color(0, 10, 125));
        tblCargos.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tblCargos.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tblCargos.setShowGrid(true);
        tblCargos.setShowHorizontalLines(false);
        tblCargos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblCargosMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblCargos);

        pnl_visualizar.add(jScrollPane2);
        jScrollPane2.setBounds(0, 110, 770, 170);

        jLabel3.setFont(new java.awt.Font("SansSerif", 3, 18)); // NOI18N
        jLabel3.setText("R$");
        pnl_visualizar.add(jLabel3);
        jLabel3.setBounds(410, 335, 40, 40);

        jtf_Filtro.setBackground(new java.awt.Color(181, 210, 255));
        jtf_Filtro.setFont(new java.awt.Font("SansSerif", 3, 16)); // NOI18N
        jtf_Filtro.setBorder(null);
        jtf_Filtro.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jtf_Filtro.setEnabled(false);
        jtf_Filtro.setMaximumSize(new java.awt.Dimension(63, 25));
        jtf_Filtro.setMinimumSize(new java.awt.Dimension(63, 25));
        jtf_Filtro.setPreferredSize(new java.awt.Dimension(63, 25));
        jtf_Filtro.setVerifyInputWhenFocusTarget(false);
        jtf_Filtro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtf_FiltroKeyReleased(evt);
            }
        });
        pnl_visualizar.add(jtf_Filtro);
        jtf_Filtro.setBounds(150, 60, 490, 25);

        jtf_nomeEditar.setBackground(new java.awt.Color(217, 227, 244));
        jtf_nomeEditar.setFont(new java.awt.Font("SansSerif", 3, 18)); // NOI18N
        jtf_nomeEditar.setBorder(null);
        pnl_visualizar.add(jtf_nomeEditar);
        jtf_nomeEditar.setBounds(40, 340, 310, 30);

        jtf_valorEditar.setBackground(new java.awt.Color(217, 227, 244));
        jtf_valorEditar.setFont(new java.awt.Font("SansSerif", 3, 18)); // NOI18N
        jtf_valorEditar.setBorder(null);
        jtf_valorEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtf_valorEditarActionPerformed(evt);
            }
        });
        pnl_visualizar.add(jtf_valorEditar);
        jtf_valorEditar.setBounds(440, 340, 280, 30);

        btn_editar.setBackground(new java.awt.Color(91, 225, 64));
        btn_editar.setFont(new java.awt.Font("SansSerif", 1, 25)); // NOI18N
        btn_editar.setForeground(new java.awt.Color(255, 255, 255));
        btn_editar.setText("Editar");
        btn_editar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_editarActionPerformed(evt);
            }
        });
        pnl_visualizar.add(btn_editar);
        btn_editar.setBounds(420, 400, 150, 70);
        btn_editar.getAccessibleContext().setAccessibleDescription("");

        btn_excluir.setBackground(new java.awt.Color(199, 52, 86));
        btn_excluir.setFont(new java.awt.Font("SansSerif", 1, 25)); // NOI18N
        btn_excluir.setForeground(new java.awt.Color(255, 255, 255));
        btn_excluir.setText("Excluir");
        btn_excluir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_excluir.setPreferredSize(new java.awt.Dimension(75, 25));
        btn_excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_excluirActionPerformed(evt);
            }
        });
        pnl_visualizar.add(btn_excluir);
        btn_excluir.setBounds(600, 400, 150, 70);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/LBL_ProcurarCargo.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        pnl_visualizar.add(jLabel1);
        jLabel1.setBounds(130, 0, 520, 110);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/LBL_Valor.png"))); // NOI18N
        jLabel4.setText("jLabel4");
        pnl_visualizar.add(jLabel4);
        jLabel4.setBounds(390, 300, 350, 80);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/LBL_Nomes.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        pnl_visualizar.add(jLabel2);
        jLabel2.setBounds(20, 300, 350, 80);

        pnl_background.add(pnl_visualizar);
        pnl_visualizar.setBounds(0, 60, 770, 510);
        pnl_visualizar.getAccessibleContext().setAccessibleDescription("");

        getContentPane().add(pnl_background);
        pnl_background.setBounds(440, 170, 770, 570);

        jlb_voltar3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/BTN_voltar.png"))); // NOI18N
        jlb_voltar3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jlb_voltar3.setOpaque(true);
        jlb_voltar3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlb_voltar3MouseClicked(evt);
            }
        });
        getContentPane().add(jlb_voltar3);
        jlb_voltar3.setBounds(440, 45, 100, 90);

        jlb_image32.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/LBL_Cargos.png"))); // NOI18N
        getContentPane().add(jlb_image32);
        jlb_image32.setBounds(545, 40, 590, 100);

        jlb_image3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/SFP_Cargo.png"))); // NOI18N
        getContentPane().add(jlb_image3);
        jlb_image3.setBounds(0, -10, 425, 780);

        jlb_branco3.setBackground(new java.awt.Color(255, 255, 255));
        jlb_branco3.setOpaque(true);
        getContentPane().add(jlb_branco3);
        jlb_branco3.setBounds(0, 0, 1250, 780);

        setSize(new java.awt.Dimension(1347, 788));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jlb_cadastrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlb_cadastrarMouseClicked
        pnl_default.setVisible(false);
        pnl_cadastrar.setVisible(true);
        pnl_visualizar.setVisible(false);
        jlb_cadastrar.setBackground(new Color(25,39,70));
        jlb_cadastrar.setForeground(Color.white);
        jlb_visualizar.setBackground(new Color(181,210,255));
        jlb_visualizar.setForeground(new Color(25,39,70));
        jtf_nome.setEnabled(true);
        jtf_codigo.setEnabled(true);
        jtf_salario.setEnabled(true);
    }//GEN-LAST:event_jlb_cadastrarMouseClicked

    private void btn_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_cancelarActionPerformed

    private void btn_salvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_salvarActionPerformed
                String nome;
		float valor_hr;
		
		nome = jtf_nome.getText();
		valor_hr = Float.parseFloat(jtf_salario.getText());
        
		//salvar informacoes no banco
		Cargo cargo = new Cargo(nome, valor_hr);
		CargoDAO dao = new CargoDAO();
		//System.out.println(dao.salvar(cargo));
                JOptionPane.showMessageDialog(null, dao.salvar(cargo));
                
                jtf_nome.setText("");
                jtf_salario.setText("");
    }//GEN-LAST:event_btn_salvarActionPerformed

    private void jlb_visualizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlb_visualizarMouseClicked
        pnl_default.setVisible(false);
        pnl_cadastrar.setVisible(false);
        pnl_visualizar.setVisible(true);
        jlb_cadastrar.setBackground(new Color(181,210,255));
        jlb_cadastrar.setForeground(new Color(25,39,70));
        jlb_visualizar.setBackground(new Color(25,39,70));
        jlb_visualizar.setForeground(Color.white);
        jtf_Filtro.setEnabled(true);
        preencherTab();
    }//GEN-LAST:event_jlb_visualizarMouseClicked

    private void jlb_voltar3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlb_voltar3MouseClicked
        TelaPrincipal principal = new TelaPrincipal(acesso);
            principal.setVisible(true);
            this.dispose();
    }//GEN-LAST:event_jlb_voltar3MouseClicked

    private void jtf_FiltroKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtf_FiltroKeyReleased
        preencherTab();
    }//GEN-LAST:event_jtf_FiltroKeyReleased

    private void tblCargosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblCargosMouseClicked
        if (tblCargos.getSelectedRow() != -1){
        codCargo = Integer.parseInt(tblCargos.getValueAt(tblCargos.getSelectedRow(), 0).toString());
	jtf_nomeEditar.setText(tblCargos.getValueAt(tblCargos.getSelectedRow(), 1).toString());
	jtf_valorEditar.setText(tblCargos.getValueAt(tblCargos.getSelectedRow(), 2).toString());      
}
    }//GEN-LAST:event_tblCargosMouseClicked

    private void btn_editarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editarActionPerformed
        String nome;
        float valor;
        
        nome = jtf_nomeEditar.getText();
	valor = Float.parseFloat(jtf_valorEditar.getText());
        Cargo cargo = new Cargo(nome, valor);
        
        CargoDAO dao = new CargoDAO();
        JOptionPane.showMessageDialog(null, dao.editar(cargo, codCargo));
        
        jtf_nomeEditar.setText("");
        jtf_valorEditar.setText("");
        
        preencherTab();
    }//GEN-LAST:event_btn_editarActionPerformed

    private void btn_excluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_excluirActionPerformed
        CargoDAO dao = new CargoDAO();
        JOptionPane.showMessageDialog(null, dao.excluir(codCargo));
        jtf_nomeEditar.setText("");
        jtf_valorEditar.setText("");
        
        preencherTab();
    }//GEN-LAST:event_btn_excluirActionPerformed

    private void jtf_valorEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtf_valorEditarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_valorEditarActionPerformed

    /**
     * Busca os dados no banco para preenchimento de tabela
     */
     private void preencherTab()
    {
        CargoDAO cargo = new CargoDAO();
        String nomeCargo = jtf_Filtro.getText();
        List<Cargo> listaCargos = cargo.pesquisar(nomeCargo);
        
        DefaultTableModel tabelaCargos = (DefaultTableModel) tblCargos.getModel();
        
        tabelaCargos.setNumRows(0);
        for (Cargo c : listaCargos)
        {
            Object[] obj = new Object[]{
            
            c.getCodigo(), c.getNome(), c.getValor_hr()};
            
            tabelaCargos.addRow(obj);
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCargo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCargo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCargo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCargo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCargo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cancelar;
    private javax.swing.JButton btn_editar;
    private javax.swing.JButton btn_excluir;
    private javax.swing.JButton btn_salvar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel jlb_branco3;
    private javax.swing.JLabel jlb_cadastrar;
    private javax.swing.JLabel jlb_image3;
    private javax.swing.JLabel jlb_image32;
    private javax.swing.JLabel jlb_nome;
    private javax.swing.JLabel jlb_salario;
    private javax.swing.JLabel jlb_visualizar;
    private javax.swing.JLabel jlb_voltar3;
    private javax.swing.JTextField jtf_Filtro;
    private javax.swing.JTextField jtf_codigo;
    private javax.swing.JTextField jtf_nome;
    private javax.swing.JTextField jtf_nomeEditar;
    private javax.swing.JTextField jtf_salario;
    private javax.swing.JTextField jtf_valorEditar;
    private javax.swing.JPanel pnl_background;
    private javax.swing.JPanel pnl_cadastrar;
    private javax.swing.JPanel pnl_default;
    private javax.swing.JPanel pnl_visualizar;
    private javax.swing.JTable tblCargos;
    // End of variables declaration//GEN-END:variables
}
