/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package telas;

import banco.CargoDAO;
import banco.FuncionarioDAO;
import entidades.Cargo;
import entidades.Funcionario;
import java.awt.Color;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.ZoneId;
import java.time.format.DateTimeFormatter;
import java.util.Date;
import java.util.List;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Abner
 */
public class TelaFuncionario extends javax.swing.JFrame {

    int nivelSenioridade = 1, codCargo, codFunc, acesso;
    Vector<Integer> codigos = new Vector<Integer>();
    
    /**
     * Creates new form TelaFuncionario
     */
    public TelaFuncionario() {
        initComponents();
    }

    public TelaFuncionario(int acesso) {
        initComponents();
        this.acesso = acesso;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnl_backgroundFunc = new javax.swing.JPanel();
        jlb_visualizarFunc = new javax.swing.JLabel();
        jlb_cadastrarFunc = new javax.swing.JLabel();
        pnl_defaultFunc = new javax.swing.JPanel();
        pnl_visualizarFunc = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblFuncionarios = new javax.swing.JTable();
        jtf_Filtro = new javax.swing.JTextField();
        jtf_nomeEditar = new javax.swing.JTextField();
        jtf_CPFEditar = new javax.swing.JTextField();
        jtf_nascEditar = new javax.swing.JTextField();
        jtf_contratEditar = new javax.swing.JTextField();
        jtf_depEditar = new javax.swing.JTextField();
        btn_editar = new javax.swing.JButton();
        btn_excluir = new javax.swing.JButton();
        jrb_juniorEditar = new javax.swing.JRadioButton();
        jrb_plenoEditar = new javax.swing.JRadioButton();
        jrb_seniorEditar = new javax.swing.JRadioButton();
        jcb_cargoEditar = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        pnl_cadastrarFunc = new javax.swing.JPanel();
        jtf_nomeFunc = new javax.swing.JTextField();
        jtf_cpfFunc = new javax.swing.JTextField();
        jtf_contratacaoFunc = new javax.swing.JTextField();
        jtf_dependentesFunc = new javax.swing.JTextField();
        jtf_nascimentoFunc = new javax.swing.JTextField();
        jlb_datasFunc = new javax.swing.JLabel();
        jlb_dependentesFunc = new javax.swing.JLabel();
        jlb_nomeFunc = new javax.swing.JLabel();
        jlb_cpfFunc = new javax.swing.JLabel();
        jlb_senioridadeFunc = new javax.swing.JLabel();
        btn_cancelarFunc = new javax.swing.JButton();
        btn_salvarFunc = new javax.swing.JButton();
        jrb_juniorFunc = new javax.swing.JRadioButton();
        jrb_plenoFunc = new javax.swing.JRadioButton();
        jrb_seniorFunc = new javax.swing.JRadioButton();
        jcb_cargo = new javax.swing.JComboBox();
        jlb_image42 = new javax.swing.JLabel();
        jlb_voltar4 = new javax.swing.JLabel();
        jlb_image4 = new javax.swing.JLabel();
        jlb_branco4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        pnl_backgroundFunc.setBackground(new java.awt.Color(181, 210, 255));
        pnl_backgroundFunc.setLayout(null);

        jlb_visualizarFunc.setBackground(new java.awt.Color(181, 210, 255));
        jlb_visualizarFunc.setFont(new java.awt.Font("SansSerif", 3, 18)); // NOI18N
        jlb_visualizarFunc.setForeground(new java.awt.Color(25, 39, 70));
        jlb_visualizarFunc.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlb_visualizarFunc.setText("VISUALIZAR FUNCIONÁRIO");
        jlb_visualizarFunc.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jlb_visualizarFunc.setOpaque(true);
        jlb_visualizarFunc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlb_visualizarFuncMouseClicked(evt);
            }
        });
        pnl_backgroundFunc.add(jlb_visualizarFunc);
        jlb_visualizarFunc.setBounds(390, 0, 380, 60);

        jlb_cadastrarFunc.setBackground(new java.awt.Color(181, 210, 255));
        jlb_cadastrarFunc.setFont(new java.awt.Font("SansSerif", 3, 18)); // NOI18N
        jlb_cadastrarFunc.setForeground(new java.awt.Color(25, 39, 70));
        jlb_cadastrarFunc.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlb_cadastrarFunc.setText("CADASTRAR FUNCIONÁRIO");
        jlb_cadastrarFunc.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jlb_cadastrarFunc.setOpaque(true);
        jlb_cadastrarFunc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlb_cadastrarFuncMouseClicked(evt);
            }
        });
        pnl_backgroundFunc.add(jlb_cadastrarFunc);
        jlb_cadastrarFunc.setBounds(0, 0, 380, 60);

        pnl_defaultFunc.setBackground(new java.awt.Color(255, 255, 255));
        pnl_defaultFunc.setEnabled(false);
        pnl_defaultFunc.setFocusable(false);
        pnl_defaultFunc.setRequestFocusEnabled(false);
        pnl_defaultFunc.setVerifyInputWhenFocusTarget(false);
        pnl_backgroundFunc.add(pnl_defaultFunc);
        pnl_defaultFunc.setBounds(0, 0, 770, 570);

        pnl_visualizarFunc.setBackground(new java.awt.Color(181, 210, 255));
        pnl_visualizarFunc.setMinimumSize(new java.awt.Dimension(770, 510));
        pnl_visualizarFunc.setLayout(null);

        tblFuncionarios.setBackground(new java.awt.Color(86, 153, 220));
        tblFuncionarios.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        tblFuncionarios.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        tblFuncionarios.setForeground(new java.awt.Color(255, 255, 255));
        tblFuncionarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Código", "Nome", "CPF", "Data de nascimento", "Data de contratação", "Dependentes"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblFuncionarios.setMaximumSize(new java.awt.Dimension(215, 104));
        tblFuncionarios.setRowHeight(26);
        tblFuncionarios.setSelectionBackground(new java.awt.Color(255, 255, 255));
        tblFuncionarios.setSelectionForeground(new java.awt.Color(0, 10, 125));
        tblFuncionarios.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tblFuncionarios.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tblFuncionarios.setShowGrid(true);
        tblFuncionarios.setShowVerticalLines(false);
        tblFuncionarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblFuncionariosMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblFuncionarios);

        pnl_visualizarFunc.add(jScrollPane2);
        jScrollPane2.setBounds(0, 100, 770, 130);

        jtf_Filtro.setBackground(new java.awt.Color(181, 210, 255));
        jtf_Filtro.setFont(new java.awt.Font("SansSerif", 3, 16)); // NOI18N
        jtf_Filtro.setActionCommand("<Not Set>");
        jtf_Filtro.setBorder(null);
        jtf_Filtro.setEnabled(false);
        jtf_Filtro.setMaximumSize(new java.awt.Dimension(63, 25));
        jtf_Filtro.setMinimumSize(new java.awt.Dimension(63, 25));
        jtf_Filtro.setPreferredSize(new java.awt.Dimension(63, 25));
        jtf_Filtro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtf_FiltroKeyReleased(evt);
            }
        });
        pnl_visualizarFunc.add(jtf_Filtro);
        jtf_Filtro.setBounds(150, 56, 490, 25);

        jtf_nomeEditar.setBackground(new java.awt.Color(217, 227, 244));
        jtf_nomeEditar.setFont(new java.awt.Font("SansSerif", 3, 12)); // NOI18N
        jtf_nomeEditar.setBorder(null);
        jtf_nomeEditar.setMinimumSize(new java.awt.Dimension(64, 15));
        jtf_nomeEditar.setName(""); // NOI18N
        jtf_nomeEditar.setPreferredSize(new java.awt.Dimension(64, 15));
        pnl_visualizarFunc.add(jtf_nomeEditar);
        jtf_nomeEditar.setBounds(30, 265, 300, 15);

        jtf_CPFEditar.setBackground(new java.awt.Color(217, 227, 244));
        jtf_CPFEditar.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jtf_CPFEditar.setBorder(null);
        jtf_CPFEditar.setMinimumSize(new java.awt.Dimension(64, 15));
        jtf_CPFEditar.setName(""); // NOI18N
        jtf_CPFEditar.setPreferredSize(new java.awt.Dimension(64, 15));
        pnl_visualizarFunc.add(jtf_CPFEditar);
        jtf_CPFEditar.setBounds(390, 265, 300, 15);

        jtf_nascEditar.setBackground(new java.awt.Color(217, 227, 244));
        jtf_nascEditar.setFont(new java.awt.Font("SansSerif", 3, 12)); // NOI18N
        jtf_nascEditar.setBorder(null);
        jtf_nascEditar.setMinimumSize(new java.awt.Dimension(64, 15));
        jtf_nascEditar.setPreferredSize(new java.awt.Dimension(64, 15));
        pnl_visualizarFunc.add(jtf_nascEditar);
        jtf_nascEditar.setBounds(30, 330, 300, 16);

        jtf_contratEditar.setBackground(new java.awt.Color(217, 227, 244));
        jtf_contratEditar.setFont(new java.awt.Font("SansSerif", 3, 12)); // NOI18N
        jtf_contratEditar.setBorder(null);
        pnl_visualizarFunc.add(jtf_contratEditar);
        jtf_contratEditar.setBounds(390, 330, 300, 16);

        jtf_depEditar.setBackground(new java.awt.Color(217, 227, 244));
        jtf_depEditar.setFont(new java.awt.Font("SansSerif", 3, 12)); // NOI18N
        jtf_depEditar.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtf_depEditar.setBorder(null);
        pnl_visualizarFunc.add(jtf_depEditar);
        jtf_depEditar.setBounds(25, 397, 165, 20);

        btn_editar.setBackground(new java.awt.Color(91, 225, 64));
        btn_editar.setFont(new java.awt.Font("SansSerif", 1, 25)); // NOI18N
        btn_editar.setForeground(new java.awt.Color(255, 255, 255));
        btn_editar.setText("Editar");
        btn_editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_editarActionPerformed(evt);
            }
        });
        pnl_visualizarFunc.add(btn_editar);
        btn_editar.setBounds(400, 430, 150, 50);
        btn_editar.getAccessibleContext().setAccessibleName("EDITAR");

        btn_excluir.setBackground(new java.awt.Color(199, 52, 86));
        btn_excluir.setFont(new java.awt.Font("SansSerif", 1, 25)); // NOI18N
        btn_excluir.setForeground(new java.awt.Color(255, 255, 255));
        btn_excluir.setText("Excluir");
        btn_excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_excluirActionPerformed(evt);
            }
        });
        pnl_visualizarFunc.add(btn_excluir);
        btn_excluir.setBounds(565, 430, 150, 50);

        jrb_juniorEditar.setFont(new java.awt.Font("SansSerif", 3, 16)); // NOI18N
        jrb_juniorEditar.setText("Junior");
        jrb_juniorEditar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jrb_juniorEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrb_juniorEditarActionPerformed(evt);
            }
        });
        pnl_visualizarFunc.add(jrb_juniorEditar);
        jrb_juniorEditar.setBounds(385, 385, 98, 26);

        jrb_plenoEditar.setFont(new java.awt.Font("SansSerif", 3, 16)); // NOI18N
        jrb_plenoEditar.setText("Pleno");
        jrb_plenoEditar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jrb_plenoEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrb_plenoEditarActionPerformed(evt);
            }
        });
        pnl_visualizarFunc.add(jrb_plenoEditar);
        jrb_plenoEditar.setBounds(510, 385, 80, 26);
        jrb_plenoEditar.getAccessibleContext().setAccessibleName(" Pleno");

        jrb_seniorEditar.setFont(new java.awt.Font("SansSerif", 3, 16)); // NOI18N
        jrb_seniorEditar.setText("Senior");
        jrb_seniorEditar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jrb_seniorEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrb_seniorEditarActionPerformed(evt);
            }
        });
        pnl_visualizarFunc.add(jrb_seniorEditar);
        jrb_seniorEditar.setBounds(630, 385, 90, 26);

        jcb_cargoEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcb_cargoEditarActionPerformed(evt);
            }
        });
        pnl_visualizarFunc.add(jcb_cargoEditar);
        jcb_cargoEditar.setBounds(17, 460, 185, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/LBL_ProcurarNome.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        pnl_visualizarFunc.add(jLabel1);
        jLabel1.setBounds(130, 10, 520, 90);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Tela_EditarFuncionário.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        pnl_visualizarFunc.add(jLabel2);
        jLabel2.setBounds(0, 230, 760, 280);

        pnl_backgroundFunc.add(pnl_visualizarFunc);
        pnl_visualizarFunc.setBounds(0, 60, 770, 510);

        pnl_cadastrarFunc.setBackground(new java.awt.Color(181, 210, 255));
        pnl_cadastrarFunc.setLayout(null);

        jtf_nomeFunc.setBackground(new java.awt.Color(181, 210, 255));
        jtf_nomeFunc.setFont(new java.awt.Font("SansSerif", 3, 16)); // NOI18N
        jtf_nomeFunc.setAutoscrolls(false);
        jtf_nomeFunc.setBorder(null);
        jtf_nomeFunc.setEnabled(false);
        pnl_cadastrarFunc.add(jtf_nomeFunc);
        jtf_nomeFunc.setBounds(40, 100, 660, 30);

        jtf_cpfFunc.setBackground(new java.awt.Color(181, 210, 255));
        jtf_cpfFunc.setFont(new java.awt.Font("SansSerif", 3, 16)); // NOI18N
        jtf_cpfFunc.setAutoscrolls(false);
        jtf_cpfFunc.setBorder(null);
        jtf_cpfFunc.setEnabled(false);
        pnl_cadastrarFunc.add(jtf_cpfFunc);
        jtf_cpfFunc.setBounds(40, 200, 310, 30);

        jtf_contratacaoFunc.setBackground(new java.awt.Color(181, 210, 255));
        jtf_contratacaoFunc.setFont(new java.awt.Font("SansSerif", 3, 16)); // NOI18N
        jtf_contratacaoFunc.setAutoscrolls(false);
        jtf_contratacaoFunc.setBorder(null);
        jtf_contratacaoFunc.setEnabled(false);
        pnl_cadastrarFunc.add(jtf_contratacaoFunc);
        jtf_contratacaoFunc.setBounds(480, 303, 210, 30);

        jtf_dependentesFunc.setBackground(new java.awt.Color(181, 210, 255));
        jtf_dependentesFunc.setFont(new java.awt.Font("SansSerif", 3, 16)); // NOI18N
        jtf_dependentesFunc.setAutoscrolls(false);
        jtf_dependentesFunc.setBorder(null);
        jtf_dependentesFunc.setEnabled(false);
        pnl_cadastrarFunc.add(jtf_dependentesFunc);
        jtf_dependentesFunc.setBounds(410, 200, 310, 30);

        jtf_nascimentoFunc.setBackground(new java.awt.Color(181, 210, 255));
        jtf_nascimentoFunc.setFont(new java.awt.Font("SansSerif", 3, 16)); // NOI18N
        jtf_nascimentoFunc.setAutoscrolls(false);
        jtf_nascimentoFunc.setBorder(null);
        jtf_nascimentoFunc.setEnabled(false);
        pnl_cadastrarFunc.add(jtf_nascimentoFunc);
        jtf_nascimentoFunc.setBounds(200, 303, 210, 30);

        jlb_datasFunc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/LBL_Datas.png"))); // NOI18N
        pnl_cadastrarFunc.add(jlb_datasFunc);
        jlb_datasFunc.setBounds(20, 250, 720, 110);

        jlb_dependentesFunc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/LBL_Dependentes.png"))); // NOI18N
        jlb_dependentesFunc.setText("NOME");
        jlb_dependentesFunc.setOpaque(true);
        pnl_cadastrarFunc.add(jlb_dependentesFunc);
        jlb_dependentesFunc.setBounds(390, 160, 355, 80);

        jlb_nomeFunc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/LBL_Nome.png"))); // NOI18N
        pnl_cadastrarFunc.add(jlb_nomeFunc);
        jlb_nomeFunc.setBounds(20, 40, 720, 110);

        jlb_cpfFunc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/LBL_CPF.png"))); // NOI18N
        jlb_cpfFunc.setText("CPF");
        jlb_cpfFunc.setOpaque(true);
        pnl_cadastrarFunc.add(jlb_cpfFunc);
        jlb_cpfFunc.setBounds(20, 160, 355, 80);

        jlb_senioridadeFunc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/LBL_Senioridades.png"))); // NOI18N
        jlb_senioridadeFunc.setText("SENIORIDADE");
        jlb_senioridadeFunc.setFocusable(false);
        jlb_senioridadeFunc.setOpaque(true);
        pnl_cadastrarFunc.add(jlb_senioridadeFunc);
        jlb_senioridadeFunc.setBounds(20, 375, 170, 40);

        btn_cancelarFunc.setBackground(new java.awt.Color(242, 172, 52));
        btn_cancelarFunc.setFont(new java.awt.Font("SansSerif", 1, 25)); // NOI18N
        btn_cancelarFunc.setText("Cancelar");
        btn_cancelarFunc.setFocusPainted(false);
        btn_cancelarFunc.setFocusable(false);
        btn_cancelarFunc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelarFuncActionPerformed(evt);
            }
        });
        pnl_cadastrarFunc.add(btn_cancelarFunc);
        btn_cancelarFunc.setBounds(565, 430, 150, 50);

        btn_salvarFunc.setBackground(new java.awt.Color(91, 225, 64));
        btn_salvarFunc.setFont(new java.awt.Font("SansSerif", 1, 25)); // NOI18N
        btn_salvarFunc.setForeground(new java.awt.Color(255, 255, 255));
        btn_salvarFunc.setText("Salvar");
        btn_salvarFunc.setFocusPainted(false);
        btn_salvarFunc.setFocusable(false);
        btn_salvarFunc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_salvarFuncActionPerformed(evt);
            }
        });
        pnl_cadastrarFunc.add(btn_salvarFunc);
        btn_salvarFunc.setBounds(400, 430, 150, 50);

        jrb_juniorFunc.setFont(new java.awt.Font("SansSerif", 1, 22)); // NOI18N
        jrb_juniorFunc.setForeground(new java.awt.Color(25, 39, 70));
        jrb_juniorFunc.setText("Junior");
        jrb_juniorFunc.setEnabled(false);
        jrb_juniorFunc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jrb_juniorFuncMouseClicked(evt);
            }
        });
        jrb_juniorFunc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrb_juniorFuncActionPerformed(evt);
            }
        });
        pnl_cadastrarFunc.add(jrb_juniorFunc);
        jrb_juniorFunc.setBounds(220, 370, 160, 50);

        jrb_plenoFunc.setFont(new java.awt.Font("SansSerif", 1, 22)); // NOI18N
        jrb_plenoFunc.setForeground(new java.awt.Color(25, 39, 70));
        jrb_plenoFunc.setText("Pleno");
        jrb_plenoFunc.setEnabled(false);
        jrb_plenoFunc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrb_plenoFuncActionPerformed(evt);
            }
        });
        pnl_cadastrarFunc.add(jrb_plenoFunc);
        jrb_plenoFunc.setBounds(350, 370, 160, 50);

        jrb_seniorFunc.setFont(new java.awt.Font("SansSerif", 1, 22)); // NOI18N
        jrb_seniorFunc.setForeground(new java.awt.Color(25, 39, 70));
        jrb_seniorFunc.setText("Sênior");
        jrb_seniorFunc.setEnabled(false);
        jrb_seniorFunc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrb_seniorFuncActionPerformed(evt);
            }
        });
        pnl_cadastrarFunc.add(jrb_seniorFunc);
        jrb_seniorFunc.setBounds(480, 370, 160, 50);

        jcb_cargo.setBackground(new java.awt.Color(86, 153, 255));
        jcb_cargo.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jcb_cargo.setForeground(new java.awt.Color(86, 153, 255));
        jcb_cargo.setToolTipText("");
        jcb_cargo.setAlignmentX(1.0F);
        jcb_cargo.setBorder(null);
        jcb_cargo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jcb_cargo.setFocusable(false);
        jcb_cargo.setRequestFocusEnabled(false);
        jcb_cargo.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jcb_cargoAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jcb_cargo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcb_cargoActionPerformed(evt);
            }
        });
        pnl_cadastrarFunc.add(jcb_cargo);
        jcb_cargo.setBounds(20, 430, 300, 50);

        pnl_backgroundFunc.add(pnl_cadastrarFunc);
        pnl_cadastrarFunc.setBounds(0, 60, 770, 510);

        getContentPane().add(pnl_backgroundFunc);
        pnl_backgroundFunc.setBounds(440, 170, 770, 570);

        jlb_image42.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/LBL_Funcionários.png"))); // NOI18N
        getContentPane().add(jlb_image42);
        jlb_image42.setBounds(545, 40, 600, 100);

        jlb_voltar4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/BTN_voltar.png"))); // NOI18N
        jlb_voltar4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jlb_voltar4.setOpaque(true);
        jlb_voltar4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlb_voltar4MouseClicked(evt);
            }
        });
        getContentPane().add(jlb_voltar4);
        jlb_voltar4.setBounds(440, 45, 100, 90);

        jlb_image4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/SFP_Funcionario.png"))); // NOI18N
        getContentPane().add(jlb_image4);
        jlb_image4.setBounds(0, -10, 425, 780);

        jlb_branco4.setBackground(new java.awt.Color(255, 255, 255));
        jlb_branco4.setOpaque(true);
        getContentPane().add(jlb_branco4);
        jlb_branco4.setBounds(0, 0, 1250, 780);

        setSize(new java.awt.Dimension(1266, 788));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jlb_voltar4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlb_voltar4MouseClicked
        TelaPrincipal principal = new TelaPrincipal(acesso);
        principal.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jlb_voltar4MouseClicked

    private void jlb_visualizarFuncMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlb_visualizarFuncMouseClicked
        pnl_defaultFunc.setVisible(false);
        pnl_cadastrarFunc.setVisible(false);
        pnl_visualizarFunc.setVisible(true);
        jlb_cadastrarFunc.setBackground(new Color(181,210,255));
        jlb_cadastrarFunc.setForeground(new Color(25,39,70));
        jlb_visualizarFunc.setBackground(new Color(25,39,70));
        jlb_visualizarFunc.setForeground(Color.white);
        jtf_Filtro.setEnabled(true);
        jtf_Filtro.setText("");
        preencherTab();
        preencherListEditar();
        
        limparEditar();
    }//GEN-LAST:event_jlb_visualizarFuncMouseClicked

    private void jlb_cadastrarFuncMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlb_cadastrarFuncMouseClicked
        pnl_defaultFunc.setVisible(false);
        pnl_cadastrarFunc.setVisible(true);
        pnl_visualizarFunc.setVisible(false);
        jlb_cadastrarFunc.setBackground(new Color(25,39,70));
        jlb_cadastrarFunc.setForeground(Color.white);
        jlb_visualizarFunc.setBackground(new Color(181,210,255));
        jlb_visualizarFunc.setForeground(new Color(25,39,70));
        jtf_nomeFunc.setEnabled(true);
        //jtf_codigoFunc.setEnabled(true);
        jtf_cpfFunc.setEnabled(true);
        jtf_dependentesFunc.setEnabled(true);
        jtf_contratacaoFunc.setEnabled(true);
        jtf_nascimentoFunc.setEnabled(true);
        jtf_cpfFunc.setEnabled(true);
        jrb_juniorFunc.setEnabled(true);
        jrb_plenoFunc.setEnabled(true);
        jrb_seniorFunc.setEnabled(true);
    }//GEN-LAST:event_jlb_cadastrarFuncMouseClicked

    private void btn_cancelarFuncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelarFuncActionPerformed

    }//GEN-LAST:event_btn_cancelarFuncActionPerformed

    private void btn_salvarFuncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_salvarFuncActionPerformed
        String nome, cpf, data;
	int dep;
        
	DateTimeFormatter format = DateTimeFormatter.ofPattern("d MMMM yyyy");		
	nome = jtf_nomeFunc.getText();
	cpf = jtf_cpfFunc.getText();
        
        //receber datas de nascimento e contratacao (convertidas) 
	data = jtf_nascimentoFunc.getText();		
	LocalDate data_nasc = LocalDate.parse(data, format);
	data = jtf_contratacaoFunc.getText();		
	LocalDate data_contrat = LocalDate.parse(data, format);
	
	dep = Integer.parseInt(jtf_dependentesFunc.getText());
		
	//converter localdate para date
	Date nasc = Date.from(data_nasc.atStartOfDay(ZoneId.systemDefault()).toInstant());
	Date contrat = Date.from(data_contrat.atStartOfDay(ZoneId.systemDefault()).toInstant());
			
	//salvar informacoes no banco
	Funcionario func = new Funcionario(nome, cpf, nasc, contrat, dep);
	FuncionarioDAO dao = new FuncionarioDAO();
	//System.out.println(dao.salvar(func));
        JOptionPane.showMessageDialog(null, dao.salvar(func));
        System.out.println(dao.atribuirSenFuncionario(cpf, nivelSenioridade, contrat));
        System.out.println(dao.atribuirCargoFuncionario(cpf, codCargo, contrat));
        
        jtf_nomeFunc.setText("");
        jtf_cpfFunc.setText("");
        jtf_contratacaoFunc.setText("");
        jtf_dependentesFunc.setText("");
        jtf_nascimentoFunc.setText("");   
        jrb_juniorFunc.setSelected(false);
        jrb_plenoFunc.setSelected(false);
        jrb_seniorFunc.setSelected(false);
        jcb_cargo.setSelectedIndex(0);
    }//GEN-LAST:event_btn_salvarFuncActionPerformed

    private void jrb_seniorFuncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrb_seniorFuncActionPerformed
        jrb_juniorFunc.setSelected(false);
        jrb_plenoFunc.setSelected(false);
        jrb_seniorFunc.setSelected(true);
        nivelSenioridade = 3;
    }//GEN-LAST:event_jrb_seniorFuncActionPerformed

    private void jrb_juniorFuncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrb_juniorFuncActionPerformed
       jrb_juniorFunc.setSelected(true);
       jrb_plenoFunc.setSelected(false);
       jrb_seniorFunc.setSelected(false);
       nivelSenioridade = 1;
    }//GEN-LAST:event_jrb_juniorFuncActionPerformed

    private void jrb_plenoFuncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrb_plenoFuncActionPerformed
        jrb_juniorFunc.setSelected(false);
        jrb_plenoFunc.setSelected(true);
        jrb_seniorFunc.setSelected(false);
        nivelSenioridade = 2;
    }//GEN-LAST:event_jrb_plenoFuncActionPerformed

    private void jrb_juniorFuncMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jrb_juniorFuncMouseClicked
        
    }//GEN-LAST:event_jrb_juniorFuncMouseClicked

    private void jtf_FiltroKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtf_FiltroKeyReleased
        preencherTab();
    }//GEN-LAST:event_jtf_FiltroKeyReleased

    private void jcb_cargoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcb_cargoActionPerformed
        Vector<Integer> codigos = new Vector<Integer>(); 
        int posicaoCargo = jcb_cargo.getSelectedIndex();
        CargoDAO c = new CargoDAO();
        codigos = c.listarCod("SELECT cod_cargo FROM cargo ORDER BY cod_cargo");
        codCargo = codigos.get(posicaoCargo);
    }//GEN-LAST:event_jcb_cargoActionPerformed

    private void jcb_cargoAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jcb_cargoAncestorAdded
        preencherList();
    }//GEN-LAST:event_jcb_cargoAncestorAdded

    private void tblFuncionariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblFuncionariosMouseClicked
        if (tblFuncionarios.getSelectedRow() != -1){
        codFunc = Integer.parseInt(tblFuncionarios.getValueAt(tblFuncionarios.getSelectedRow(), 0).toString());
	jtf_nomeEditar.setText(tblFuncionarios.getValueAt(tblFuncionarios.getSelectedRow(), 1).toString());
	jtf_CPFEditar.setText(tblFuncionarios.getValueAt(tblFuncionarios.getSelectedRow(), 2).toString());
	jtf_nascEditar.setText(tblFuncionarios.getValueAt(tblFuncionarios.getSelectedRow(), 3).toString());
        jtf_contratEditar.setText(tblFuncionarios.getValueAt(tblFuncionarios.getSelectedRow(), 4).toString());
        jtf_depEditar.setText(tblFuncionarios.getValueAt(tblFuncionarios.getSelectedRow(), 5).toString());
}
        FuncionarioDAO dao = new FuncionarioDAO();
        int senioridade = dao.consultaSenFuncionario(codFunc);
        
        switch(senioridade) {
            case 1:
                jrb_juniorEditar.setSelected(true);
                jrb_plenoEditar.setSelected(false);
                jrb_seniorEditar.setSelected(false);
            break;
            case 2:
                jrb_juniorEditar.setSelected(false);
                jrb_plenoEditar.setSelected(true);
                jrb_seniorEditar.setSelected(false);
            break;
            case 3:
                jrb_juniorEditar.setSelected(false);
                jrb_plenoEditar.setSelected(false);
                jrb_seniorEditar.setSelected(true);
            break;
}
      
      preencherListEditar();
    }//GEN-LAST:event_tblFuncionariosMouseClicked

    private void btn_editarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editarActionPerformed
        String nome, cpf;
	int dep;
        Date data_nasc = new Date();
        Date data_contrat = new Date();
        
        SimpleDateFormat formato = new SimpleDateFormat("yyyy-MM-dd"); 
        try {
            data_nasc = formato.parse(jtf_nascEditar.getText());
            data_contrat = formato.parse(jtf_contratEditar.getText());
        } catch (ParseException ex) {
            Logger.getLogger(TelaFuncionario.class.getName()).log(Level.SEVERE, null, ex);
        }
        	
        java.sql.Date nasc = new java.sql.Date(data_nasc.getTime());
        java.sql.Date contrat = new java.sql.Date(data_contrat.getTime());
        
	nome = jtf_nomeEditar.getText();
	cpf = jtf_CPFEditar.getText();
	
	dep = Integer.parseInt(jtf_depEditar.getText());

        
	//salvar informacoes no banco
	Funcionario func = new Funcionario(nome, cpf, nasc, contrat, dep);
	FuncionarioDAO dao = new FuncionarioDAO();
        JOptionPane.showMessageDialog(null, dao.editar(func, codFunc));
        Date hoje = new Date();
        System.out.println(dao.atribuirSenFuncionario(cpf, nivelSenioridade, hoje));
        System.out.println(dao.atribuirCargoFuncionario(cpf, codCargo, hoje));
        
        //limpar caixas de edicao
        limparEditar();
        
        preencherTab();
    }//GEN-LAST:event_btn_editarActionPerformed

    private void btn_excluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_excluirActionPerformed
        FuncionarioDAO dao = new FuncionarioDAO();
        JOptionPane.showMessageDialog(null, dao.excluir(codFunc));
        preencherTab();
        limparEditar();
    }//GEN-LAST:event_btn_excluirActionPerformed

    private void jrb_juniorEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrb_juniorEditarActionPerformed
        jrb_juniorEditar.setSelected(true);
        jrb_plenoEditar.setSelected(false);
        jrb_seniorEditar.setSelected(false);
        nivelSenioridade = 1;
    }//GEN-LAST:event_jrb_juniorEditarActionPerformed

    private void jrb_plenoEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrb_plenoEditarActionPerformed
        jrb_juniorEditar.setSelected(false);
        jrb_plenoEditar.setSelected(true);
        jrb_seniorEditar.setSelected(false);
        nivelSenioridade = 2;
    }//GEN-LAST:event_jrb_plenoEditarActionPerformed

    private void jrb_seniorEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrb_seniorEditarActionPerformed
        jrb_juniorEditar.setSelected(false);
        jrb_plenoEditar.setSelected(false);
        jrb_seniorEditar.setSelected(true);
        nivelSenioridade = 3;
    }//GEN-LAST:event_jrb_seniorEditarActionPerformed

    private void jcb_cargoEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcb_cargoEditarActionPerformed
        int posicaoCargo = jcb_cargoEditar.getSelectedIndex();
        CargoDAO c = new CargoDAO();
        codigos = c.listarCod("SELECT cod_cargo FROM cargo ORDER BY cod_cargo");
        codCargo = codigos.get(posicaoCargo);
    }//GEN-LAST:event_jcb_cargoEditarActionPerformed

    /**
     * Limpar caixas de texto
     */
    private void limparEditar(){
        jtf_nomeEditar.setText("");
        jtf_CPFEditar.setText("");
        jtf_nascEditar.setText("");
        jtf_contratEditar.setText("");
        jtf_depEditar.setText("");
        jtf_Filtro.setText("");
        jrb_juniorEditar.setSelected(false);
        jrb_plenoEditar.setSelected(false);
        jrb_seniorEditar.setSelected(false);
        jcb_cargoEditar.setSelectedIndex(0);
    }
    
    /**
     * Busca os dados no banco para preenchimento de lista
     */
    private void preencherList()
    {
        CargoDAO cargo = new CargoDAO();
        List<Cargo> listaCargo = cargo.listarNome("SELECT nome_cargo FROM cargo ORDER BY cod_cargo");
        
        jcb_cargo.removeAll();
        
        for (Cargo c : listaCargo)
        {
            jcb_cargo.addItem(c);
        }
    }
    
    /**
     * Busca os dados no banco para preenchimento de lista
     */
    private void preencherListEditar()
    {
        CargoDAO cargo = new CargoDAO();
        List<Cargo> listaCargo = cargo.listarNome("SELECT nome_cargo FROM cargo ORDER BY cod_cargo");
        
        jcb_cargoEditar.removeAll();
        
        for (Cargo c : listaCargo)
        {
            jcb_cargoEditar.addItem(c);
        }
        
        FuncionarioDAO dao = new FuncionarioDAO();
        int codCargo = dao.consultaCargoFuncionarioCod(codFunc);
        int cargoIndex = -1;
        for (int i =0; i<=codigos.size(); i++){
            if (codigos.elementAt(i)==codCargo){
                cargoIndex = i;
                break;
            }
        }
        
        jcb_cargoEditar.setSelectedIndex(cargoIndex);
    }
    
   /**
    * Busca os dados no banco para preenchimento de tabela
    */
   private void preencherTab()
    {
        FuncionarioDAO func = new FuncionarioDAO();
        String nomeFunc = jtf_Filtro.getText();
        List<Funcionario> listaFuncionarios = func.pesquisar(nomeFunc);
        
        DefaultTableModel tabelaFuncionarios = (DefaultTableModel) tblFuncionarios.getModel();
        
        tabelaFuncionarios.setNumRows(0);
        for (Funcionario f : listaFuncionarios)
        {
            Object[] obj = new Object[]{
            
            f.getCodigo(), f.getNome(), f.getCpf(), f.getData_nasc(),
            f.getData_contrat(), f.getDependentes()};
            
            tabelaFuncionarios.addRow(obj);
        }

    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaFuncionario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cancelarFunc;
    private javax.swing.JButton btn_editar;
    private javax.swing.JButton btn_excluir;
    private javax.swing.JButton btn_salvarFunc;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JComboBox jcb_cargo;
    private javax.swing.JComboBox jcb_cargoEditar;
    private javax.swing.JLabel jlb_branco4;
    private javax.swing.JLabel jlb_cadastrarFunc;
    private javax.swing.JLabel jlb_cpfFunc;
    private javax.swing.JLabel jlb_datasFunc;
    private javax.swing.JLabel jlb_dependentesFunc;
    private javax.swing.JLabel jlb_image4;
    private javax.swing.JLabel jlb_image42;
    private javax.swing.JLabel jlb_nomeFunc;
    private javax.swing.JLabel jlb_senioridadeFunc;
    private javax.swing.JLabel jlb_visualizarFunc;
    private javax.swing.JLabel jlb_voltar4;
    private javax.swing.JRadioButton jrb_juniorEditar;
    private javax.swing.JRadioButton jrb_juniorFunc;
    private javax.swing.JRadioButton jrb_plenoEditar;
    private javax.swing.JRadioButton jrb_plenoFunc;
    private javax.swing.JRadioButton jrb_seniorEditar;
    private javax.swing.JRadioButton jrb_seniorFunc;
    private javax.swing.JTextField jtf_CPFEditar;
    private javax.swing.JTextField jtf_Filtro;
    private javax.swing.JTextField jtf_contratEditar;
    private javax.swing.JTextField jtf_contratacaoFunc;
    private javax.swing.JTextField jtf_cpfFunc;
    private javax.swing.JTextField jtf_depEditar;
    private javax.swing.JTextField jtf_dependentesFunc;
    private javax.swing.JTextField jtf_nascEditar;
    private javax.swing.JTextField jtf_nascimentoFunc;
    private javax.swing.JTextField jtf_nomeEditar;
    private javax.swing.JTextField jtf_nomeFunc;
    private javax.swing.JPanel pnl_backgroundFunc;
    private javax.swing.JPanel pnl_cadastrarFunc;
    private javax.swing.JPanel pnl_defaultFunc;
    private javax.swing.JPanel pnl_visualizarFunc;
    private javax.swing.JTable tblFuncionarios;
    // End of variables declaration//GEN-END:variables
}
